default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: uvote

development:
  <<: *default
  database: uvote_development

test:
  <<: *default
  database: uvote_test

production:
  <<: *default
  database: uvote_production
  password: <%= ENV['uvote_DATABASE_PASSWORD'] %>